services:
#    commission.example:
#        class: CommissionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    service.commission:
        class: CommissionBundle\Services\CommissionService
        arguments: ["@doctrine.orm.entity_manager", "@serializer"]
